### ISSUE TITLE
Wrong bench by 1 user stops test

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#100]
This feature is fine except that if only 1 user has wrong bench, the test should not stop right away.

For months there is 2 or 3 workers which constantly stops tests because using the signature from the run they just finished !

**Comment by pb00068** [comment]
To me it sounds like these workers fail to download the new executables (base & stockfish) so bench is performed on a executable deriving from a prior test.
Can anybody confirm this?

Also this issue is similar to #145, 
Once we have fixed it, probably it becomes easy to apply the same (or similar) logic to the executables.

**Comment by ppigazzini** [comment]
@vondele if I'm not wrong the worker write the file testing/results.pgn , so running two instances in the same folder should still be a no go.

**Comment by vondele** [comment]
@ppigazzini that's correct, and I don't recommend running two workers in the same directory, but as far as I know, testing/results.pgn is a write only file and never used. So, the file will be garbage...but this fact wont affect the data obtained from the worker.

**Comment by ppigazzini** [comment]
@vondele OK, thank you.

**Comment by Lolligerhans** [comment]
I seem to experience the same problem. Test gets aborted after 300 games from invalid bench. Test: http://tests.stockfishchess.org/tests/view/5cd365110ebc5925cf04a237
