### ISSUE TITLE
Remove unused option

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#124]
When we create a new test, the very first item is a drop down list choice between "Standard" and "Regression". The "Regression" choice is undocumented, unused, and confusing for new testers. It should be removed.

**Comment by ianfab** [comment]
I agree, and I think there are three options:
1. only remove the option from the test submission page, but keep it in the backend (e.g., for later reuse)
2. completely remove all code related to it
3. turn it into a useful distinct test type

Unless there is a good suggestion for the third option, I would go for the first one. If that is desirable, I can create a PR for it. I would keep the select box for now though, but having only one option ("Standard"). That would be a minimal and easily reversible change.

**Comment by Stefano80** [comment]
Why not option 2) ?

**Comment by ianfab** [comment]
This issue is mainly about usability and 1) would be the easiest way to improve it, but for maintaining 2) would perhaps be beneficial if we do not consider reintroducing it at a later point. If we go for 2) the question is whether we also want to remove `test_type` as a whole, i.e., also removing "Standard".

**Comment by Stefano80** [comment]
I would remove everything, if this does not break backwards compatibility.

**Comment by Rocky640** [comment]
I will close this issue, since it has been fixed.
