### ISSUE TITLE
cutechess-cli issues: running fishtest with MSYS/MINGW/CYGWIN

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#126]
There is a problem running fishtest with msys, mingw or Cygwin on windows
cause fishtest downloading cutechess-cli for linux always:

Step 4/4. Deleting profile data ...
make ARCH=x86-64-modern COMP=gcc profileclean
make[1]: Entering directory '/tmp/tmpAWGApv/syzygy1-Stockfish-2198cd0/src'
make[1]: Leaving directory '/tmp/tmpAWGApv/syzygy1-Stockfish-2198cd0/src'
Downloading 2moves_v1.pgn ...
Downloading cutechess-cli-linux-64bit.zip ...

So we have an exception due to running alien binary...
But there is no any problem to compile cutechess for such environments with:
$ git clone https://github.com/cutechess/cutechess.git

So I compiled optimized static binaries with mingw(MSYS2) and qt5-static pacman package w/o any problems:

[cutechess-cli-windows-64bit.zip](https://github.com/glinscott/fishtest/files/1594308/cutechess-cli-windows-64bit.zip)
[cutechess-cli-windows-32bit.zip](https://github.com/glinscott/fishtest/files/1594309/cutechess-cli-windows-32bit.zip)

As workaround you can use this binaries:  just delete Linux cutechess-cli into fishtest/worker/testing/ directory and copy cutechess-cli.exe here.

So you can run fishtest w/o problems now..

Moreover my qt5 cutechess builds works into one binary faster then into official fishtest windows package which consist with qt4, msvc, etc dlls.

**Comment by ppigazzini** [comment]
fishtest runs fine on Windows (and download the correct cutechess-cli for windows) if installed using the wiki instruction (portable installer, or manual installation).

Your problem could be due to the python distribution, simply open a python cli and run
```python
import platform
platform.system().lower()
```
On my system:
* python from python.org returns `windows` as expected from the fishtest's code
* python from msys2 returns 'mingw64_nt-10.0', so fishtest think that the system is linux

ps:
to run fishtest using msys2's python:
* change [line 29](https://github.com/glinscott/fishtest/blob/master/worker/games.py#L29) with `IS_WINDOWS = 'windows' in platform.system().lower() or 'mingw' in platform.system().lower()`
* change [line 50](https://github.com/glinscott/fishtest/blob/master/worker/games.py#L50) with `MAKE_CMD = 'make profile-build COMP=mingw ' + ARCH`
* change [line 157](https://github.com/glinscott/fishtest/blob/master/worker/games.py#L157) with `subprocess.call(['taskkill', '//F', '//T', '//PID', str(p.pid)])`
* change [lines 91-92](https://github.com/glinscott/fishtest/blob/master/worker/games.py#L91-L92) with `busy_process.communicate('quit\n')` 
* use a static build of an up to date cutechess-cli

**Comment by ppigazzini** [comment]
@d3vv I discovered that msys2 provides also a mingw64 python3 package and this works fine in fishtest without any code change (better to use a Qt5 cutechess-cli, though). I already updated the wiki page to simplify the worker setup on Windows:
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows
