### ISSUE TITLE
SPSA Autoselect is still optimized for "noob_3moves.epd"

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#1327]
https://github.com/glinscott/fishtest/blob/4709fa65250248d27d9c6587286437c92ee6acab/server/fishtest/static/js/spsa_new.js#L101-L105

But now we are using "UHO_XXL_+0.90_+1.19.epd".

Some references:
https://github.com/glinscott/fishtest/issues/535#issuecomment-653418155

**Comment by G-Lorenz** [comment]
Discussion started on Discord (https://discord.com/channels/435943710472011776/900771437177094156/966753330003058718) with this question:

Having 0.61 as default draw_ratio in spsa (instead of ~0.47) can be a problem? https://github.com/glinscott/fishtest/blob/4709fa65250248d27d9c6587286437c92ee6acab/server/fishtest/static/js/spsa_new.js#L61
Probably is more used this function (https://github.com/glinscott/fishtest/blob/4709fa65250248d27d9c6587286437c92ee6acab/server/fishtest/static/js/spsa_new.js#L163-L174) but the issue persists: the spsa draw ratio estimate seems to be based on noob_3moves while now we use UHO for tuning...

Followed by:
draw_ratio(tc) was tested at 5 different tc (1+0.01, 10+0.1, 20+0.2, 60+0.6 and 120+1.2: https://github.com/glinscott/fishtest/issues/535#issuecomment-653418155).
Current STC and LTC tests shows more or less draw_ratio=0.47.
So I don't know if we can just assume 0.47 everywhere for our testing purposes.

**Comment by G-Lorenz** [comment]
According to local testing draw ratio starts to sensibly decreasing with tc smaller than 0.5+0.005.

Submitted test at 120+1.2: https://tests.stockfishchess.org/tests/view/62627310d6f0fbbf61fd1a62

**Comment by cw-sf** [comment]
Some more draw ratio examples for other TCs:

TC 2+0.02 draw ratio 0.46860
https://tests.stockfishchess.org/tests/stats/61a7e3a04ed77d629d4e6c27 

TC 5+0.05 draw ratio 0.44643
https://tests.stockfishchess.org/tests/stats/61fad11fd508ec6a1c9ef93b

TC 180+1.8 draw ratio 0.48280
https://tests.stockfishchess.org/tests/stats/62120c34b1792e8985f89b1a

**Comment by G-Lorenz** [comment]
Draw ratio of balanced (+-2 Elo) tests with UHO book seems to be near 0.46, 0.47 at all tested tc.

According to https://github.com/vdbergh/spsa_simul/blob/master/doc/theoretical_basis.pdf if an unbalanced book is used is better to replace `draw_ratio` with `draw_ratio + 4 * RMS_bias^2`. Using recent stc and ltc yellow tests, my 120+1.2 fixed games test and the fixed games test at 2+0.02 found by cw-sf, I obtain the following values for the `draw_ratio` formula in spsa_new.js:
`slope = 0.188`
`intercept = 1.288`
![corr_draw_ratio](https://user-images.githubusercontent.com/73311422/164889956-ee1b5ca0-2563-4aef-b0c2-2872f29ddd42.png)

If we decide to use the corrected draw ratio I suggest to run a test at 30+0.3 (tc often used by fauzi) in order to check the validity of the fit (4 data points are too few...)

**Comment by ppigazzini** [comment]
@vdbergh please review at your convenient time :)

**Comment by vdbergh** [comment]
@ppigazzini I am a bit busy know but mathematically it is not difficult. The factor `1-d` in the formulas should be replaced by 4 times the pentanomial variance/game. One can check for the tests with noob book that this is almost the same as `1-d`. But it is very different for the UHO book. 

The pentanomial variance per game can be found in the raw statistics page. One should collect some data points for different tc and then interpolate.

**Comment by vdbergh** [comment]
@G-Lorenz Thanks for running the test at 120+1.2. I am currently running 2+0.02.

**Comment by G-Lorenz** [comment]
Thank you @vdbergh !

So now we have:
2+0.02 (200k games master vs master): https://tests.stockfishchess.org/tests/view/62650ce760f74bf0dfac5313
30+0.3 (10k games master vs master): https://tests.stockfishchess.org/tests/view/6263da23fe69c0c878b85295
120+1.2 (10k games master vs master): https://tests.stockfishchess.org/tests/view/62627310d6f0fbbf61fd1a62

And many recent yellow stc and ltc, such as:
STC yellow (130k games, against master): https://tests.stockfishchess.org/tests/stats/626367c8fe69c0c878b84019
LTC yellow (130k games, against last merged net): https://tests.stockfishchess.org/tests/stats/625e9dcce7b02dbe28c9b86e

**Comment by G-Lorenz** [comment]
Updated and corrected graph (new formula, error bars, 30+0.3 at 0.74s/move)
![Cdr3](https://user-images.githubusercontent.com/73311422/165062097-76ca1cab-a608-4106-8273-5057d3038dee.png)
results: `slope=0.22`; `intercept=1.31`.
I'm going to test at 20+0.2 (tc often used).

**Comment by vdbergh** [comment]
@G-Lorenz I would recommend using the formula 
```
(virtual) draw ratio = 1-4*(variance per game)
```
It is more accurate than the formula `draw_ratio + 4 * RMS_bias^2` (the latter is nice for theoretical purposes).

**Comment by vdbergh** [comment]
Deleted wrong comment.

**Comment by vdbergh** [comment]
@G-Lorenz I recommend making a PR when the current tests finish!

**Comment by vdbergh** [comment]
5+0.05 https://tests.stockfishchess.org/tests/view/6266f2c8ba1d917675ac0a86
