### ISSUE TITLE
Endgame suite for fishtest

### ISSUE THREAD

**Issue by Stefano80** [glinscott/fishtest#139]
This is moved from here.

We should have a endgame test suite with early endgames (10-16 men) from complex positions for specific tests on the framework.

There has been a first idea from @Mindbreaker1.

I think the zip posted by you is a good starting point. Could you merge all pgn into one? I think we should'nt have dozens of suite but just one.

Also I am thinking that we should have something like 16 men maximum, but in your suite we have up to 24 men. Could you reduce it to say a suite with < 20 men? Otherwise we end up with a midgame test suite.

**Comment by Mindbreaker1** [comment]
Many different files is exactly what we need.  If you want to see if some code will help R v R endgames (w/ pawns), what could be better than testing it with just R v R positions?  If it is opposite color Bishop ending code, then use opposite color bishop positions.  If something is good for general endgames, then it will pass the usual tests just fine.  It might go faster with just endgame positions, but it should have no bearing on the result.  The problem with code for specific endgames is that those positions will come up rarely in a typical test and any result will be impossible to detect though the noise of all the other games.
[Endgame.zip](https://github.com/glinscott/fishtest/files/2104971/Endgame.zip)
Each file can be reduced in size by removing duplicates.  I suspect there are many many duplicate positions.  Maybe 80% or more are duplicates in any given file.  The duplicate removing utilities only look for duplicate games rather than duplicate positions.
In testing, I suppose it would make sense to use the relevant book to see if there is improvement at STC and LTC, but then use the normal 2-move book to be sure there is no general regression at LTC.

**Comment by vondele** [comment]
this is a pretty old PR, meanwhile there is an endgames book on fishtest, obviously as non-default. I think this can be closed.
