### ISSUE TITLE
fishtest server log shows error

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#1636]
```
Apr 26 20:20:27 tests pserve[2224]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/mako/runtime.py", line 916, in _render_context
Apr 26 20:20:27 tests pserve[2224]:     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
Apr 26 20:20:27 tests pserve[2224]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/mako/runtime.py", line 943, in _exec_template
Apr 26 20:20:27 tests pserve[2224]:     callable_(context, *args, **kwargs)
Apr 26 20:20:27 tests pserve[2224]:   File "/home/fishtest/fishtest/server/fishtest/templates/base.mak", line 264, in render_body
Apr 26 20:20:27 tests pserve[2224]:     <div>${self.body()}</div>
Apr 26 20:20:27 tests pserve[2224]:   File "/home/fishtest/fishtest/server/fishtest/templates/tests_user.mak", line 8, in render_body
Apr 26 20:20:27 tests pserve[2224]:     <%include file="run_tables.mak"/>
Apr 26 20:20:27 tests pserve[2224]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/mako/runtime.py", line 793, in _include_file
Apr 26 20:20:27 tests pserve[2224]:     callable_(ctx, **kwargs)
Apr 26 20:20:27 tests pserve[2224]:   File "/home/fishtest/fishtest/server/fishtest/templates/run_tables.mak", line 10, in render_body
Apr 26 20:20:27 tests pserve[2224]:     <% pending_approval_runs = [run for run in runs['pending'] if not run['approved']] %>
Apr 26 20:20:27 tests pserve[2224]: TypeError: 'Undefined' object is not subscriptable
```

I read this as `runs` being undefined at this point. In general this error is not happening, so I wonder if this could be a race of some sorts?

**Comment by ppigazzini** [comment]
https://github.com/glinscott/fishtest/blob/0d4736423cbea49fb8ed1c4698cc68746b3943c0/server/fishtest/views.py#L1362-L1377

**Comment by ppigazzini** [comment]
This should fix the problem (not the race):

```python
 % if page_idx == 0: 
     <% pending_approval_runs = [run for run in runs['pending'] if (run is not None and not run['approved'])] %> 
     <% paused_runs = [run for run in runs['pending'] if (run is not None and run['approved'])] %> 
```

**Comment by peregrineshahin** [comment]
Can this already happen when there is no pending tests or no paused tests?

**Comment by peregrineshahin** [comment]
I.e if runs["pending"] doesn't exist fro some reason?
I mean I'm not a python genius but it seems like this pending should at least be an empty array for current code not to bug out. No?

**Comment by vdbergh** [comment]
> I.e if runs["pending"] doesn't exist fro some reason?
> I mean I'm not a python genius but it seems like this pending should at least be an empty array for current code not to bug out. No?

runs["pending"] is initialized as an empty list.

**Comment by vdbergh** [comment]
@ppigazzini Can you explain what precisely is the race?

**Comment by vondele** [comment]
I guess that's hypothetical, based on my initial comment. It is somewhat hard to see how this could go wrong unless `response["runs"]` is somehow different from expected.

**Comment by ppigazzini** [comment]
Yes, hypothetical based on Joost's comment.
And my proposed fix should not work, because the original error message is `TypeError: 'Undefined' object is not subscriptable`. So in that point of time we tried to access an element in a non built-in object that doesn't support indexing.

```python
a = [[0], [1], None, [3]]
b = [i for i in a if i[0] > 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
TypeError: 'NoneType' object is not subscriptable
```

**Comment by peregrineshahin** [comment]
The only way I could think about reproducing that is if someone explicitly requested something like this
Or else it's a race condition because pending and paused lists are indeed initialized to my eyes.

Suppose
Trying this
https://tests.stockfishchess.org/tests/user/linrock?page=-9 // Crashes (expected to show in events log)
https://tests.stockfishchess.org/tests/user/linrock?page=0 // Crashes (expected to show in events log)
https://tests.stockfishchess.org/tests/user/linrock?page=1 // does not crash

Trying this
https://tests.stockfishchess.org/tests?page=-9 // Does not crash
https://tests.stockfishchess.org/tests?page=0 // Does not crash
https://tests.stockfishchess.org/tests?page=1 // Does not crash

The difference being
The first is comparing with `if int(request.params.get("page", 1)) == 1:` to show unfinished runs
while the second is comparing with `if int(request.params.get("page", 1)) > 1:` to show finished runs (i.e allowing 0 and negative to pass)

and since this request.params.get("page", 1) is independent of the `% if page_idx == 0:` we use in the renderer I expect it to be actually true when we use something like ?page=-9 and thus 
```
    if int(request.params.get("page", 1)) == 1:
        response["runs"] = request.rundb.aggregate_unfinished_runs(
            username=username,
        )[0]
```
will not execute resulting in a crash of this request. (e.g. https://tests.stockfishchess.org/tests/user/linrock?page=-9) but needs to be confirmed if this actually show the same thing in the logs :)

**Comment by ppigazzini** [comment]
Confirmed in log!
