### ISSUE TITLE
Delete binaries cache on worker startup

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#1666]
As people have now the option to change the compiler used by the worker, it is possible that SF binaries generated by different compilers are kept in the testing_dir. This could result an incorrect test with binaries generated by different compilers. The easiest solution is to delete the cache of binaries at worker startup.

I'll have a look at that solution.

**Comment by vdbergh** [comment]
A binary generated by a different compiler is still a valid binary IMHO. If the binary is broken it will be detected further down the line.

Also: the server remembers which binaries the worker has (because of the rate limit). If the worker systematically deletes binaries at start up, this feature will not work anymore.

**Comment by vondele** [comment]
The binary is not broken, but might have a different speed. E.g. master could be a gcc binary that is 10% slower than a clang binary. Any test would pass on this worker. This would be just a one-time clean at worker startup.

**Comment by vdbergh** [comment]
Ok. Actually my other concern isn't valid because if the worker is restarted its UUID changes. The prefix stays the same but this is not used as the key.

Doesn't the SF binary know the compiler it was compiled with? Or could the compiler command line be incorporated in the hash? That would allow for a less incisive change.

**Comment by vondele** [comment]
some information about the compiler is in the binary, but we might not have the details. It seems less error prone to just reset the cache. Having to compile a binary is a relatively small overhead compared to how infrequent it is to restart the worker.
