### ISSUE TITLE
Large tuning still cripples the server

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#253]
It is however strange that I do not see any actual network failures on my proxy between workers to the server, so it is just the server isn't giving responses in time.

**Comment by tomtor** [comment]
And #254

**Comment by tomtor** [comment]
@ppigazzini I have fishtest running with pypy:
- download and extract https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.10.0-linux64.tar.bz2 in $HOME
- install virtualenv (distribution version or with pip)
- virtualenv -p ~/pypy2-v5.10.0-linux64/bin/pypy pypy
- source pypy/bin/activate 
- pip install numpy
- pypy setup.py install
- pypy /usr/local/bin/pserve production.ini

**Comment by tomtor** [comment]
@ppigazzini An additional advantage of pypy installation is that you also get new versions of all used Python packages in a separate environment.

**Comment by noobpwnftw** [comment]
I see, is it then possible to limit the number of concurrent tuning tasks? Like we could have something similar to the throughput setting so that no more than X tasks should run. It is also useful to other tasks, like we don't want to have every worker assigned to one single long-running test.

**Comment by tomtor** [comment]
@noobpwnftw 

> I see, is it then possible to limit the number of concurrent tuning tasks? Like we could have something similar to the throughput setting so that no more than X tasks should run. It is also useful to other tasks, like we don't want to have every worker assigned to one single long-running test.

Sure, but not just as fix to the current issue which should/could be solved by a different Python stack.

The issue with limiting the number of workers for each run is that the only situation in which a run gets all the workers is simply when there are no other runnable runs.  So what should we do in that situation? Leave 80% of the workers idle? Once workers are allocated to a run they should finish their allocated task, because the credits and priority calculations are currently based on workers completing their 1000 game tasks. Fixing those calculations would allow stopping workers without these drawbacks. Lowering the batch size to eg 500 is also an option as has been proposed on the forum.

**Comment by ppigazzini** [comment]
@tomtor thank you for the suggestion. I will have some spare time during the week end to test this (and the mongo db upgrade) on a new dev server installed with CentOS 6.8.

**Comment by ppigazzini** [comment]
@tomtor anyway, what is the advantage of using pypy? Also with python 2.7 from the software collections should be possible to have a clean fishtest install with updated packages.

**Comment by tomtor** [comment]
@ppigazzini On average pypy is 7 times faster then cpython 2.7. For a web framework like django even 20x. That is a BIG difference and would allow us to do more compute intensive things in fishtest. 

I really wonder what the root cause for the slow big spsa runs is. Currently the prod server is very slow again. :-/

**Comment by vondele** [comment]
@tomtor I notice there are now more machines on fishtest than usually (1578 cores / 200 machines). However, the SPSA runs might not be the issue. I have a feeling that as soon as I was able to approve a pending SPRT run the situation improved. My feeling is that the issue appears when there are more workers than available batches (i.e. only fixed number of games ttests). Can it be that idle workers overload the server ?

**Comment by vondele** [comment]
in fact, the SPRT test failed quickly, and now the server is slowly responding again.

**Comment by noobpwnftw** [comment]
@vondele It is because when the workers fail to report their progress(due to time out), they remain assigned until scavenge.py cleans them up. When you assign more SPRT tests, those workers may get assigned there instead of the SPSA run, effectively reducing load, when that test failed they are back to where they were.

**Comment by noobpwnftw** [comment]
At this moment, about 500 cores are assigned to two SPRT tests, meaning those will not create more load with the SPSA test, and they were idle

**Comment by vondele** [comment]
right, and as soon as these two sprts were approved, the responsiveness of the server improved again (slow but better). I'm not sure I could follow your explanation, but I assume @tomtor does.

**Comment by tomtor** [comment]
I think we have eliminated MongoDb bandwidth and cpu load as causes. That leaves network IO for uploading and downloading the param data as last cause for the trouble on the production server...

**Comment by ppigazzini** [comment]
ATM server unresponsive, here the output of `free` and `top`
```
             total       used       free     shared    buffers     cached
Mem:       3145728    2876236     269492       6468          0    1752124
-/+ buffers/cache:    1124112    2021616
Swap:            0          0          0
```

```
top - 10:33:10 up 6 days, 18:23,  2 users,  load average: 4.79, 6.29, 6.48
Tasks:  24 total,   1 running,  23 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  4.0%sy, 32.7%ni, 63.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  2864916k used,   280812k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1744368k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
25367 fishtest  25   5 1752m 886m 4236 S 113.6 28.8 701:27.64 python
  649 fishtest  25   5 12.7g 351m 222m S  3.0 11.4   1382:05 mongod
    1 root      20   0 19232  736  496 S  0.0  0.0   0:00.49 init
```

**Comment by noobpwnftw** [comment]
This CPU issue indicates only a few portion of code are running in parallel, no way the server become unresponsive when only one thread hanging. Might be a pserve or framework issue, not something we did wrong though.

**Comment by ppigazzini** [comment]
The production server is responsive w/ ssh and other programs.

I have updated the [dev server](http://94.198.98.239/tests) with a fresh copy of the DB and the big SPSA run at 1+0.01 to raise the network load. @noobpwnftw could you try to kill the dev server w/ 50, 100 and 200 workers?

As usual I added these users:
- approver:
  usr: user00  prd: user00
- normal user:
  usr: user01  prd: user01

**Comment by tomtor** [comment]
Note that normally a multithreaded Python program can only have one active thread in the interpreter due to the GIL (Global Interpreter Lock).

That is in most real life setups no problem because threads are normally waiting for network/database IO or execute in external libraries which do the heavy lifting, but a CPU usage >= 100% is REALLY a problem in fishtest context. The SPSA calculations are not very expensive on my system, just checked and request_spsa takes 1.5ms, that would be around 3ms on the production server. So 100s of iterations per second should be no issue. Using pypy would improve this even more (a factor 5-10 would not surprise me).

It suspect the production server has an issue with the large JSON marshalling/unmarshalling due to an inefficiency in the used software versions.

**Comment by noobpwnftw** [comment]
My workers are on dev server now. @ppigazzini

**Comment by tomtor** [comment]
@ppigazzini The very short TC 1+0.01 causes artifacts, because the end-time of the game of the workers is exceeded. With 50 workers TC 3+0.03 or something like that would give a more realistic setting

**Comment by ppigazzini** [comment]
@tomtor add a SPSA @ 3+0.03 and changed priority

**Comment by ppigazzini** [comment]
this is the situation of the production server python packages.
`sudo pip install pip --upgrade` broke pip (reinstalled after a clean by hand) so I'm a bit worried to update the packages...

```
 pip list --outdated
You are using pip version 7.1.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
distribute (Current: 0.6.45 Latest: 0.7.3 [sdist])
Could not find a version that satisfies the requirement fishtest-server (from versions: )
pyramid-debugtoolbar (Current: 1.0.6 Latest: 4.4 [wheel])
Pygments (Current: 1.6 Latest: 2.2.0 [wheel])
pymongo (Current: 2.5.2 Latest: 3.6.1 [sdist])
Could not find a version that satisfies the requirement yum-metadata-parser (from versions: )
psutil (Current: 1.1.3 Latest: 5.4.5 [sdist])
Could not find a version that satisfies the requirement setools (from versions: )
MarkupSafe (Current: 0.18 Latest: 1.0 [sdist])
Could not find a version that satisfies the requirement policycoreutils-default-encoding (from versions: )
pygpgme (Current: 0.1 Latest: 0.3 [sdist])
zope.interface (Current: 4.0.5 Latest: 4.5.0 [sdist])
pyzmq (Current: 13.1.0 Latest: 17.0.0 [sdist])
scipy (Current: 0.7.2 Latest: 1.0.1 [sdist])
numpy (Current: 1.4.1 Latest: 1.14.2 [sdist])
pycurl (Current: 7.19.0 Latest: 7.43.0.1 [sdist])
zope.deprecation (Current: 4.0.2 Latest: 4.3.0 [wheel])
tornado (Current: 3.1 Latest: 5.0.2 [sdist])
setuptools (Current: 0.6rc11 Latest: 39.0.1 [wheel])
venusian (Current: 1.0a8 Latest: 1.1.0 [wheel])
translationstring (Current: 1.1 Latest: 1.3 [wheel])
PasteDeploy (Current: 1.5.0 Latest: 1.5.2 [wheel])
Mako (Current: 0.8.1 Latest: 1.0.7 [sdist])
WebOb (Current: 1.2.3 Latest: 1.8.1 [wheel])
waitress (Current: 0.8.5 Latest: 1.1.0 [wheel])
pyramid (Current: 1.4.2 Latest: 1.9.2 [wheel])
unittest2 (Current: 0.5.1 Latest: 1.1.0 [wheel])
boto (Current: 2.9.5 Latest: 2.48.0 [wheel])
Chameleon (Current: 2.11 Latest: 3.2 [sdist])
urlgrabber (Current: 3.9.1 Latest: 3.10.2 [sdist])
pip (Current: 7.1.0 Latest: 10.0.1 [wheel])
nose (Current: 0.10.4 Latest: 1.3.7 [wheel])
iniparse (Current: 0.3.1 Latest: 0.4 [sdist])
repoze.lru (Current: 0.6 Latest: 0.7 [sdist])
requests (Current: 1.2.3 Latest: 2.18.4 [wheel])
```

**Comment by ppigazzini** [comment]
@tomtor the SPSA @ 1+0.01 reports 0 time losses and 0 crashes, I don't understand the "end-time of the game of the workers is exceeded"

**Comment by vondele** [comment]
If you want my 2cents (not an expert). I think it might be a good time to change the production server to the same software level of the dev server. For this, it would also be absolutely normal to have a planned 1 day maintenance break in normal operation of the production server.

**Comment by tomtor** [comment]
@ppigazzini See https://github.com/glinscott/fishtest/blob/f2308e6097a8d4212d44a34b3242434965230259/worker/games.py#L264

Cutechess keeps on playing while the worker Python code waits for communication. If cutechess has finished the worker will terminate.

**Comment by ppigazzini** [comment]
@glinscott should rebuild the VM with CentOS 7.x after a DB backup (`mongodump`). With my setup script the server will be online in max 30 minutes (`mongorestore --drop` to import the db).
As alternative I could host also the production server on my ISP, in that case we should update the DNS and I should have a look at the S3 backup.

**Comment by tomtor** [comment]
I would currently leave all Python packages as is on the production server (because we just demonstrated that the development server has similar issues, ie fishtest Python CPU not below 100%) and try creating a new pypy installation as described earlier in this thread.

No risk, because it does not touch any files that are currently used and if it works you have probably a significant performance boost AND up-to-date Python packages in your pypy virtual environment.

**Comment by ppigazzini** [comment]
@tomtor OK, I will try to setup pypy during the week end.
@noobpwnftw you can switch your workers to fishtest, thank you!

**Comment by tomtor** [comment]
Some profiling output after 170 iterations/350 games played and some main and tests view:

http://vmprof.com/#/9be02913-bd23-4e39-b8f5-39cc10a81f6b

I will create a longer test run...

**Comment by noobpwnftw** [comment]
@tomtor How does this work: you mentioned GIL, so if the python code is calling a synchronous MongoDB function, does it hold the GIL or the external function would run asynchronously and then wakes up the python code upon completion?

If that is the case, I do not understand how come when the server is loaded by SPSA, even the login page takes longer to response...

**Comment by tomtor** [comment]
When communicating with MongoDb that specific thread goes to sleep, the GIL is released and the CPU is available for other threads. The login page takes longer because no unused CPU cycles are available. They are almost all used processing the JSON and the main page renderer has to wait until it gets it share of CPU-slices.

**Comment by noobpwnftw** [comment]
I recall solving a similar case in PHP with a POSIX flock and memcached, then I can run multiple interpreter processes.

**Comment by tomtor** [comment]
> So it basically a single-core preempting scheduler? That's FAKE multi-threading...

Yes, that's how it works. That is no issue with IO bound jobs, but you don't want cpu intensive jobs in the Python code. Note that Numpy or Google tensorflow are high performant and very popular Python libraries which do the heavy lifting in C or even in the GPU, but use Python for glueing the parts together.

**Comment by noobpwnftw** [comment]
If I read that perf map correctly, then everything ended up blue can be "multi-threaded", we need to reduce the pink blocks that does not end up with a blue block, which is pymongo(under authenticate)?

**Comment by tomtor** [comment]
It is a bit more complicated, because you cannot allocate Python data structures (eg the result of the JSON unmarshalling) without acquiring the GIL (which exists solely for that purpose). Note that manipulating the shared sprt or spsa data structures should be single threaded even if all code was written in C. So to really be scalable for a single run an entirely different design is needed. Multiple runs could just get their own server. But all overkill for our current context...

**Comment by tomtor** [comment]
https://wtanaka.com/node/8100 could be interesting as replacement for transmitting large sprt messages.
