### ISSUE TITLE
Elo page not correct after test is finished

### ISSUE THREAD

**Issue by Stefano80** [glinscott/fishtest#263]
Hi I just noticed that after the test is finished, the Elo diffused l displayed in the Elo page for sprt tests is wrong.

**Comment by tomtor** [comment]
How is it wrong? Can you paste a screen dump?

**Comment by vondele** [comment]
@Stefano80 this is actually correct....the page correct computes elo after SPRT. This means that even though the number of wins is larger than losses, the elo can be negative for a [-3,1] SPRT run. If we're pedantic, it is actually the coloring of boxes that is wrong.

**Comment by Stefano80** [comment]
It sounds like some a posteriori estimation. What is the prior?

**Comment by vondele** [comment]
For the precise explanation you'll have to ask vdberg. However, the intuitive one is that the data has been obtained after a sprt, and in particular for a long (limit infinity) running sprt run we know that the (bayes)elo estimate if very close to the middle of the interval (so -1 bayeselo for a [-3,1]), otherwise the pass/fail decision would have been made much earlier.

**Comment by vdbergh** [comment]
@Stefano80  I am a rather surprised by this out of the blue non-issue as this discussion has been going on for years and I have explained it many times already. So let me be brief this time.

Live elo implements a version of the formula in Corollary III.3.45 in the standard text book "Sequential Analysis. Tests and confidence intervals." by David Siegmnd. Actually before I became aware of this book (I am not a statistician) I derived a similar formula myself. You can find an old (badly written) version of this here  http://hardy.uhasselt.be/Toga/support_random_walk.pdf .

Let me finally say that the confidence intervals, the point estimate and the p-value (1-LOS) computed by live_elo.html have been confirmed by simulation.

The python source code is here 

http://hardy.uhasselt.be/Toga/sprt_elo.py

**Comment by Stefano80** [comment]
Ok thank you! I appear to have missed the discussion in the past years.

Do we want to change the colouring of the boxes in the fishtest page? Maybe it makes more sense to colour it according to expected Elo being positive or negative, rather than score.

**Comment by vondele** [comment]
@Stefano80 ...  That would make some sense for [0, N] tests, but would lead to confusion for [-3, 1] tests, as a negative elo [-3, 1] can still be a passing test.

**Comment by Stefano80** [comment]
I see. The point is that 4 colours are needed to display all combinations of Elo and passing status, but only three have an intuitive meaning. Mmmhhh...

**Comment by vdbergh** [comment]
@Stefano80 No one  should not change the red/green coloring of the boxes since these indicate succes or failure, which is the primary outcome of the test. Note that the elo estimate comes with a confidence interval and in your example, even though the point estimate is negative, the confidence interval still contains positive values.

**Comment by vondele** [comment]
Anyway, we shouldn't forget that the error bars on elo estimates are almost always to large to be interesting, especially for 'yellow' tests...

**Comment by Stefano80** [comment]
No new ideas, closing.
