### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#283]
When a test has wrong bench, it is detected, and eventually ends in the "Fail" section.
So far, so good.

However if a test does not compile, it will stay there forever, will be picked up by workers which can't compile it, until it is manually stopped.

Is there a way to stop this automatically ?

**Comment by vondele** [comment]
In principle yes, but there is one possible issue. If one worker has problems to compile (e.g. old buggy compiler), full file system, etc., it will stop this test (or any test) from running. This is actually more common, e.g. tuning  tests do not compile with lto + profile-use with the system compiler on ubuntu 14.

If we want to prevent this, we could require that a test passes travis (since that's a controlled environment) before it can be approved. The disadvantage is that it actually takes too long for our usual process of submitting tests quite quickly.
