### ISSUE TITLE
Tighter Time Controls

### ISSUE THREAD

**Issue by Chess13234** [glinscott/fishtest#338]
The problem with STC/LTC time controls is that they introduce too much randomness into searched depth. Engines given unequal time slices behaves very differently, especially when eval score influence time allocated per move.
The solution i propose is changing time controls to reduce move time variability, making average move times more uniform, which would make comparing engine strength(the actual goal, instead of comparing better time management) much easier, since SPRT isn't distorted by random wins/losses due time slice allocation randomly influencincing ELO. 

The replacement for STC 10+0.1 could be either
1+0.15 or 1+0.2
The replacement for LTC 60+0.6 would be either
2+0.9 or 2+1
The replacement for VLTC 120+1.2 would be either
4+1.8 or 4+2
The replacement to VVLTC(240+2.4) would be either
8+3.5 or 8+4
Both changes will use less time for shorter games and slightly more time for longer games.
Moves and Maximum Game durations in seconds. 
Duration table  | Move Counts
-------------------  | ---------------- 
Time Controls  | Maximum Duration in Seconds 

Game Duration | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 | 110 | 120 | 130 | 140 | 150 | 160 | 170 | 180 | 190 | 200 | 210 | 220 | 230 | 240 | 250
-------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | --------------
10+0.1 | 22 | 24 | 26 | 28 | 30 | 32 | 34 | 36 | 38 | 40 | 42 | 44 | 46 | 48 | 50 | 52 | 54 | 56 | 58 | 60 | 62 | 64 | 66 | 68 | 70
1+0.15 | 5 | 8 | 11 | 14 | 17 | 20 | 23 | 26 | 29 | 32 | 35 | 38 | 41 | 44 | 47 | 50 | 53 | 56 | 59 | 62 | 65 | 68 | 71 | 74 | 77
1+0.2 | 6 | 10 | 14 | 18 | 22 | 26 | 30 | 34 | 38 | 42 | 46 | 50 | 54 | 58 | 62 | 66 | 70 | 74 | 78 | 82 | 86 | 90 | 94 | 98 | 102
20+0.2 | 44 | 48 | 52 | 56 | 60 | 64 | 68 | 72 | 76 | 80 | 84 | 88 | 92 | 96 | 100 | 104 | 108 | 112 | 116 | 120 | 124 | 128 | 132 | 136 | 140
1+0.25  | 7 | 12 | 17 | 22 | 27 | 32 | 37 | 42 | 47 | 52 | 57 | 62 | 67 | 72 | 77 | 82 | 87 | 92 | 97 | 102 | 107 | 112 | 117 | 122 | 127
1+0.3  | 8 | 14 | 20 | 26 | 32 | 38 | 44 | 50 | 56 | 62 | 68 | 74 | 80 | 86 | 92 | 98 | 104 | 110 | 116 | 122 | 128 | 134 | 140 | 146 | 152
60+0.6 | 132 | 144 | 156 | 168 | 180 | 192 | 204 | 216 | 228 | 240 | 252 | 264 | 276 | 288 | 300 | 312 | 324 | 336 | 348 | 360 | 372 | 384 | 396 | 408 | 420 
2+0.9 | 22 | 40 | 58 | 76 | 94 | 112 | 130 | 148 | 166 | 184 | 202 | 220 | 238 | 256 | 274 | 292 | 310 | 328 | 346 | 364 | 382 | 400 | 418 | 436 | 454 
2+1 | 24 | 44 | 64 | 84 | 104 | 124 | 144 | 164 | 184 | 204 | 224 | 244 | 264 | 284 | 304 | 324 | 344 | 364 | 384 | 404 | 424 | 444 | 464 | 484 | 504 
120+1.2 | 264 | 288 | 312 | 336 | 360 | 384 | 408 | 432 | 456 | 480 | 504 | 528 | 552 | 576 | 600 | 624 | 648 | 672 | 696 | 720 | 744 | 768 | 792 | 816 | 840 
4+1.8 | 44 | 80 | 116 | 152 | 188 | 224 | 260 | 296 | 332 | 368 | 404 | 440 | 476 | 512 | 548 | 584 | 620 | 656 | 692 | 728 | 764 | 800 | 836 | 872 | 908 
4+2  | 48 | 88 | 128 | 168 | 208 | 248 | 288 | 328 | 368 | 408 | 448 | 488 | 528 | 568 | 608 | 648 | 688 | 728 | 768 | 808 | 848 | 888 | 928 | 968 | 1008 
240+2.4 | 528 | 576 | 624 | 672 | 720 | 768 | 816 | 864 | 912 | 960 | 1008 | 1056 | 1104 | 1152 | 1200 | 1248 | 1296 | 1344 | 1392 | 1440 | 1488 | 1536 | 1584 | 1632 | 1680 
8+3.5 | 86 | 156 | 226 | 296 | 366 | 436 | 506 | 576 | 646 | 716 | 786 | 856 | 926 | 996 | 1066 | 1136 | 1206 | 1276 | 1346 | 1416 | 1486 | 1556 | 1626 | 1696 | 1766     
8+4 | 96 | 176 | 256 | 336 | 416 | 496 | 576 | 656 | 736 | 816 | 896 | 976 | 1056 | 1136 | 1216 | 1296 | 1376 | 1456 | 1536 | 1616 | 1696 | 1776 | 1856 | 1936 | 2016

SPRT comparison between TC 10+0.1 and 1+0.15
An test that should fail SPRT(recently tuned Rook value is increased by 100 centipawns).
In Time Control 10+0.1
LLR: -2.96 (-2.94,2.94) [0.00,4.00]
Total: 7920 W: 1707 L: 1841 D: 4372 [red]
http://tests.stockfishchess.org/tests/view/5c1000f10ebc5902ba1187fe

in Time Control 1+0.15
LLR: -2.95 (-2.94,2.94) [0.00,4.00]
Total: 5284 W: 1287 L: 1436 D: 2561 [red]
http://tests.stockfishchess.org/tests/view/5c101d970ebc5902ba1189fc

**Comment by Vizvezdenec** [comment]
Honestly...
1) randomness in search depth is a GOOD thing in my opinion. Otherwise we will have some patches passing which are good only for some depth 15-20 and are not good for others.
2) if anything - fishtest increment is HIGH now, because you will never see any tournament with increment being 1% of total time - increasing it even further will further stretch fishtest conditions from actual tournament play.

**Comment by Chess13234** [comment]
@Vizvezdenec 
Time management introduces unequal testing conditions that distorts SPRT. With nearly equal engine scores,
If by chance either engine gets 30 milliseconds more thinking time on a critical position it could win, but this win would be purely because one engine made a deeper search, not because it magically grown extra ELO.

**Comment by Alayan-stk-2** [comment]
The concern you raise here seems very valid to me. I don't know how many games are decided because of a time fluke, but they produce statistical noise, as on average they would give a 50% score, over-evaluating elo-losing patches and under-evaluating elo-gainers.

Still, the ratio in your proposed values is quite extreme. As pointed out by Viz, 1% is already more increment than in typical tournament play. Admittedly, the point of fishtest is not to test TM on every single patch, and if some test is trying to test time management change, it could use custom appropriate TM. But 15/20% is huge, the engines would mostly play on increment in that situation, reducing fail-low/high importance.

Something which I find extremely interesting in your first message is that **you show the alternative suggested time control being able to reach the SPRT conclusion faster. Can this be reproduced reliably ?** If this is not a fluke, then maybe we could get an overall longer STC (so deeper search on average and hopefully also somewhat more consistent with a bigger increment proportion) without a big increase in resource usage, so a clear win.

And maybe something like 10+0.2 STC could offer a better balance at reducing flukes while still allowing fail-high/low to work as expected.

It seems a good idea to try several TM variants several times to get an idea of their efficiency.

**Comment by Chess13234** [comment]
Reopened  due uncovered problems in early adjudication that make current time control tests meaningless, along with problems discovered with lower bounds for SPRT that may mean these time controls have potential.

https://github.com/official-stockfish/Stockfish/issues/1904
https://github.com/official-stockfish/Stockfish/issues/1859

**Comment by Chess13234** [comment]
Reopening since new no-book test on fishtest uncovered serious issues with movetime variance.
http://tests.stockfishchess.org/tests/view/5e01c06ac13ac2425c4a9aa8
https://github.com/official-stockfish/Stockfish/issues/2283
