### ISSUE TITLE
Optimal throughput value

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#362]
Recently throughput was changed from 1000 to 10000 by default and it produced the opposite from previous problem - before we had a lot of tests not finishing because they don't get any workers and now we have a lot of tests that don't start because they don't get any workers because all workers are used by 2-3 tests that have like 50-100k games already but don't converge within this number of games.
So even after approval tests can get 0(!) workers for 2-3-4 hours. I think it's a serious issue because in most of the cases you need like 5-10k games to see if idea is a complete garbage or not but now you can wait like 5+ hours for your test to get this number of games even if fishtest is not on a heavy load.
Maybe 10000 default throughput is too high?

**Comment by vondele** [comment]
I do agree that 10000 instead of 1000 is a big change. 

One further reason for the behavior you see is manual changes in priority or throughput. If one changes e.g. priority from -1 to 0, all the 'waiting time' at prio -1 is taken into account at prio 0, and such a test will attract all workers. Similar for changes in throughput.

**Comment by vdbergh** [comment]
Long ago I proposed a credit system. Running tests would cost credit, but successful patches would earn credit (elo gainers would gain more than simplifications).  Contributing games would also earn credit. The costs would depend on the available resources (e.g. tests that are run while the framework is empty would be free).

This would a kind of regulated economy. One could also think of a true supply and demand system where people bid credits for available resources but that would be too adversarial I think.

**Comment by Vizvezdenec** [comment]
> 
> 
> I do agree that 10000 instead of 1000 is a big change.
> 
> One further reason for the behavior you see is manual changes in priority or throughput. If one changes e.g. priority from -1 to 0, all the 'waiting time' at prio -1 is taken into account at prio 0, and such a test will attract all workers. Similar for changes in throughput.

Usually this changes are made to manually throw "least useful" patches into pile of idling patches. Basically yesterday I did some manual fishtest hacking to get idling for 2-4 hours some workers.

19-01-27 01:55:36 | Vizvezdenec | soft_mc | modify: priority changed from 1 to 0
19-01-27 01:45:53 | Vizvezdenec | soft_mc | modify: priority changed from 0 to 1
19-01-27 01:43:10 | Vizvezdenec | restrictedTw1 | modify: priority changed from 1 to 0
19-01-27 01:35:17 | Vizvezdenec | restrictedTw1 | modify: priority changed from 0 to 1
19-01-27 01:34:49 | Vizvezdenec | CmplImmobPiece1 | modify: priority changed from 1 to 0
19-01-27 01:25:45 | Vizvezdenec | CmplImmobPiece1 | modify: priority changed from 0 to 1

Because this tests were having 0 workers for a long time while 2 tests with 100k~ games were regaining workers that finish the same tests.
I think that medium TP value will be better, like 2000-3000 or so.

**Comment by 31m059** [comment]
Based on what @vondele said, I'm not sure the throughput is the problem.

We initially manually increased the throughput to the new value for running tests.  Because they had been "waiting" longest, they gained high internal priority and acquired all workers.  New tests were then forced to wait.  By the time they started, they had acquired enough "waiting time" to dominate any _new_ tests, which then waited...only to later block newer tests, and so on.

What we are currently observing seems to be like a long chain of dominoes: as each one falls, it knocks down the next.

My understanding is that if the framework were to go completely empty, then this would be resolved for any new tests submitted thereafter...but a temporary moratorium on approving tests is probably too disruptive a measure to take.

**Comment by Vizvezdenec** [comment]
Not really.
With TP 1000 this never happened.
Right now if some test is running on 700 workers and second one is on 300 workers will just get reassigned to the same tests w/o new tests getting anything quite often.
With TP 1000 we had the opposite - older tests never finish and newer tests eat all workers.
So my guess is that there should be some "good" middleground with like 3000~ish default TP.

**Comment by xoto10** [comment]
All good points. 

I think the throughput makes a ceiling on how many tests can run at once, accounting for LTC tests being larger. We didn't used to notice this because the limit was so high, but now the limit seems to be roughly 3 LTC tests + 4 STC, so ~22 STC total. (I'm not sure if/how tuning fits into this, currently 3 tunes running as well, 1 LTC, 1 20+0.2 and 1 30+0.3, so maybe the limit is more like ~33 STC??)

Separately, as vondele said. I've noticed new tests grab a lot of workers at times, sometimes because the running tests have got ahead of where the throughput/priority mechanism wants them to be (because fishtest was recently quiet) so the new test appears to be "behind" - so it gets more workers. Also the priority is set relative to the start_time of the test, which could be noticeably earlier than the approval time and obviously it can't get workers until it's approved, so it is bound to be "behind" when it starts.
The whole thing runs smoother when there are several STC tests as these reallocate workers fairly regularly which helps keep things sensible, I think a lot of the odd behaviour is when there are more LTC and few STC tests.

**Comment by xoto10** [comment]
Another point is that sometimes it just takes some time for things to rebalance. Currently xoroshiro's discoExt LTC test has just over half the workers even though there are 9 other jobs running and 3 more waiting. Its priority is low enough that it will give up those workers as they finish, but because it is LTC, that takes some time, so it might take an hour or so for the workers to spread out a bit. (Also, this seems to be a good example of a new test acquiring a lot of workers.)

**Comment by Vizvezdenec** [comment]
example - right now 2/3 fishtest is busy with 30+0.3 runing with TP 6700.
Sure it's cool, but we do have flat LTC runing and it's getting 0(!) workers for 1+ hours.

**Comment by xoto10** [comment]
Yeah, tp was raised from 5000 to 6500. That meant it was way behind its expected progress compared to the other jobs, so everyone else's tests are being starved and that one test now has 738 cores ... and it will get more before it catches up to the others. I certainly wouldn't be happy if I realised I was doing that. Test author doesn't seem bothered. 
Tunes tax the fishtest infrastructure hard as well, so it might be slowing the whole system down having that many cores.

**Comment by 31m059** [comment]
@Vizvezdenec @xoto10 In my opinion, the problem is partly that speculative LTCs and non-STC tuning sessions, while certainly valuable, are being submitted with much too high throughput.

As I understood it, if a test uses _n_ times longer time control than 10+0.1, and is not directly justified by a STC green, it should be run with default / _n_ throughput:

- STC gets 10,000. 
- 20+0.2 tuning gets 5000.
- 30+0.3 gets 3333.
- 60+0.6 gets 1666, no more, unless it has a STC green.

However, this doesn't seem to be enforced, and many developers have been slowly increasing their speculative and tuning throughput.  I want to emphasize that this is not any one developer in particular, but seems to have been a framework-wide trend in recent months.  I think we need more rigorously-followed policies on throughput.

**Comment by xoto10** [comment]
@31m059 @Vizvezdenec 
Perhaps so. I haven't noticed this happening, but I do agree with the policy. If people aren't sticking to it, then they should be encouraged to do so.

This relates to what I was saying earlier about not having many stc tests running, having the longer tests run at lower throughput makes them more like stc tests, and the regular reallocation between tests helps the whole system work smoothly. This bunching of lots of workers on one test makes the whole thing clunkier, then people start manipulating their prio/throughput, etc, etc, and it all gets worse ...
If the system's not working great people should be trying to help, I lowered the throughput on a couple of my tests earlier, I didn't screw others over by raising it.

**Comment by 31m059** [comment]
@vondele Thanks, I didn't know that multithreading scaled throughput was built in.

@vondele @Vizvezdenec @xoto10 @vdbergh 
This may be a radical idea, but if non-standard TC (i.e., not strictly 10+0.1 SPRT then 60+0.1 SPRT) is here to stay--which I think it is--perhaps we should build TC scaled throughput in the same way.  Then testers deliberately raise throughput for passed-STC LTCs, and all other tests are default (or lower, of course).

In terms of human behavior, I think this has three distinct advantages.  

- First, the speculative and tuning throughput takes care of itself by default, avoiding recent ambiguities and inconsistencies.
- Second, it makes clear that we privilege LTC tests which follow passed STCs, by explicitly raising their throughput.
- Third, I think people are less likely to raise their speculative tests or tuning _above_ the default, which is an exceptional step, then they are to "below the default but maybe higher than this test should be."

**Comment by Alayan-stk-2** [comment]
@31m059 Good points !

Built-in throughput scaling depending on TC is an interesting idea to better manage resource use.

> I certainly wouldn't be happy if I realised I was doing that. Test author doesn't seem bothered.

I had lowered TP previously to let more test resources go onto STCs.

When I raised the TP, there was no STC needing quick feedback to iterate upon, the tune was 80% done and I knew that this extra oomph would allow to finish quickly enough to submit a test result before going to sleep (though I didn't expect to suck in that much cores at once). In view of how the tune had evolved, I was quite skeptical of it, but to move on to other mobility ideas I needed to get results.

> (or actually not be run at at all, since **low througput doesn't mean low resource usage... just somewhat slower**)

Important point.

**Comment by xoto10** [comment]
I see there is still a queue of tests to start, although a couple of LTCs
have finished now so hopefully things will ease a bit. There are still 3
LTCs running though, so it may take a while.

I assume there is a consensus to reduce the default throughput, what value
do we want to try? Viz suggested 3000 which seems reasonable as a mid-point
between 1000 and 10000 on an exponential scale.

To provide an alternative,  I suggest 6000 as I think this will be a
sufficient drop. If throughput limits the number of jobs before they start
queuing up, a change from 10000 to 6000 will allow a queue 67% larger, e.g.
perhaps from ~30 STC equivalent tests to ~50, which seems like a big enough
change. I don't think the difference between 3000 and 6000 will be huge, so
I'm quite happy to go with either.

**Comment by xoto10** [comment]
@31m059 @Vizvezdenec 

> - 20+0.2 tuning gets 5000.
> ...
> - 60+0.6 gets 1666, no more, unless it has a STC green.

So for example, that 60+0.6 tune that is running on tp 2500 could/should be reduced to tp 1667?

Another thing, we could try dropping the tp on one or two long-running LTC jobs to 6000 (or 3000) to see if that has a noticeable benefit?

**Comment by Alayan-stk-2** [comment]
> So for example, that 60+0.6 tune that is running on tp 2500 could/should be reduced to tp 1667?
> [Further edit: as opposed to increasing it like the ... person ... did earlier today. It seems he didn't learn anything about consideration for others yesterday.]

It seems like manually decreasing the priority of a test and then reraising it later (and I didn't do it by a lot so other tests kept running) is a fatal sin ?

I can stand argumented criticism and discussion, but this way of talking about me (not directly addressing me but instead going by things like "the person" ; and using strong accusations like the having no "consideration for others" part) foster a bad climate. Let's discuss things directly and openly instead.

**Comment by xoto10** [comment]
@Alayan-stk-2 
Ok I'll be direct. I suggest you decrease the throughput on your tune to match the normal practice 31m059 described (tp 1666).

I suggest that at a time when fishtest is slow and jobs are queueing up, it would be helpful to reduce your use of the system where possible, not increase it. As examples, one user halved the throughput on a couple of tests yesterday, another one stopped an LTC short of a probable finish today. Using 2/3 - 3/4 of the entire fishtest for an hour or two yesterday and then increasing the throughput of a large, long running job above normal practice today, for jobs which are not LTC merge candidates does not seem helpful to me. What would happen if we all grabbed more resources because they were scarce?
That doesn't mean you _have_ to do this, the senior devs seem to just go away for a day or two (or more) and let the system sort itself out, and they're perhaps the ones we should look to. But deliberately using _more_ resources for yourself, just when the system is busy, that seems selfish to me.

My apologies for not being more polite, as I am sure some of the more senior devs [would] have been.

Regarding the default throughput level I will go with Viz's suggestion and prepare a PR for 3000, let's get it changed.

**Comment by Vizvezdenec** [comment]
I think 3k TP is doing really well - patches are not hanging for days but older ones still get workers to finish. 
For now it's IMHO the optimal value.

**Comment by xoto10** [comment]
Yeah, looking good :)
