### ISSUE TITLE
invalidate main page cache on an action

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#440]
it would be nice if the main cache could be invalidated upon submission of a new test, an approval of a test, or a stop/delete of a test. Currently, the status of the main page can be a bit confusing.

Not a high prio issue, however.

**Comment by tomtor** [comment]
This is a consequence of running multiple pserve processes. The cache IS invalidated in the mutating pserve, but the main page is served from another pserve. If there is no main page currently building and the cached version is older than 2s then the main page will be build and show the latest info.

A fix would be to check if the cache is older than the most recently added/approved run by querying mongodb, instead of invalidating it in the update/create test Python code, but this would introduce more load on MongoDb. 

@ppigazzini Currently pserve is not a bottleneck, perhaps we could use just 2 pserve processes and merge the `/tests` serving pserve with the mutating pserve?

**Comment by ppigazzini** [comment]
@tomtor OK, I applied this nginx setting, let me know if it's right

```
upstream backend_runs {
    server 127.0.0.1:6543;
}

upstream backend_tests {
    server 127.0.0.1:6544;
}

upstream backend_lb {
    server 127.0.0.1:6544;
}

server {
    listen 80;
    listen [::]:80;

    server_name tests.stockfishchess.org;

    location / {
        proxy_pass http://backend_lb;
...
        location /api/active_runs {
            proxy_pass http://backend_lb;
        }

        location /api/download_pgn {
            proxy_pass http://backend_lb;
        }

        location /api/download_pgn_100 {
            proxy_pass http://backend_lb;
        }

        location /api/request_version {
            proxy_pass http://backend_lb;
        }

        location /api/upload_pgn {
            proxy_pass http://backend_lb;
        }

        location /api/ {
            proxy_pass http://backend_runs;
        }

        location /tests/user/ {
            proxy_pass http://backend_lb;
        }

        location /tests/ {
            proxy_pass http://backend_runs;
        }

        location /tests {
            proxy_pass http://backend_tests;
        }
```

**Comment by tomtor** [comment]
@ppigazzini See private mail

**Comment by tomtor** [comment]
@ppigazzini I just approved a test and that updated OK in the last config, thanks!

**Comment by ppigazzini** [comment]
@tomtor if the `upstream backend_tests` dedicated to serve `/tests` was sub optimal, we could simplify the configuration to:
```
upstream backend_runs {
    server 127.0.0.1:6543;
}

upstream backend_lb {
    server 127.0.0.1:6545;
}

server {
    listen 80;
    listen [::]:80;

    server_name tests.stockfishchess.org;

    location / {
        proxy_pass http://backend_lb;
...

        location /tests/user/ {
            proxy_pass http://backend_lb;
        }

        location /tests {
            proxy_pass http://backend_runs;
        }
...
```

**Comment by ppigazzini** [comment]
@tomtor I wrote and applied the simplified ngingx configuration, also changed to `_all` the `_lb` suffix (make no sense to balancing the pserve with 7% load :) )
