### ISSUE TITLE
SPRT trinomial code

### ISSUE THREAD

**Issue by jdart1** [glinscott/fishtest#612]
I am trying out the sprt module and it does not seem to me the LLR is computed correctly. Assuming the results are in format loss draw win, as seems to be assumed by the code, the following is what I get running the sprt module. I think the LLR should be positive. I compute LLR=0.63 using my older code (Bayes elo model). Maybe I am making a wrong assumption about the input?
```
$ python3 sprt.py --results 608 12530 648
Design parameters
=================
False positives             :  5.00%
False negatives             :  5.00%
[Elo0,Elo1]                 :  [0.00,5.00]
Confidence level            :  95.00%
Estimates
=========
Elo                         :  1.78
Confidence interval         :  [-1.65,5.55] (95.00%)
LOS                         :  84.43%
Context
=======
LLR [u,l]                   :  -2.94 (clamped) [-2.94,2.94]
```

**Comment by jdart1** [comment]
The issue seems to be with the LLR output of function sprt.analytics. (The pentanomial output is wrong, too). But calling LLRcalc.LLR_logistic, as in the Fishtest GUI code, gives the correct result.

**Comment by vdbergh** [comment]
The confusion is BayesElo versus logistic Elo. Fishtest used to use BayesElo, but not anymore.

If you assume that the inputs elo0=0,elo1=5 are in BayesElo then the LLR is indeed 0.63.

However Fishtest has recently switched to using standard logistic Elo (logistic because the correspondence elo/score is given by the logistic function). So the inputs elo0=0,elo1=5 are logistic, which leads to an LLR of -9.27.

The conversion between logistic Elo and BayesElo depends on the draw ratio which in this case is extremely high. The BayesElo values corresponding to 0,5 are 0,29 which leads to an "old style" LLR of -9.57 which is slightly different from the logistic one given above. However the method used to calculate the logistic one is more theoretically correct.

In sprt_util.py there are a number of conversion functions between BayesElo and logistic Elo.
