### ISSUE TITLE
"Missing required option when submitting spsa tests"

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#652]
Steps to reproduce:

Goto "Create New Test page"
Click SPSA button
Fill out tune options
Set "Test branch" to master
Click submit

Probably not all these steps are necessary but I have no time to debug further now.

**Comment by vondele** [comment]
seems to require explicitly the bench number...

**Comment by vdbergh** [comment]
@vondele The field is grayed out however.

**Comment by vondele** [comment]
not for the test branch ?

**Comment by vdbergh** [comment]
No. The usual "Defaults to last commit message".

I did some debugging earlier and it is really `base_signature` that is blank. I guess for spsa tests it should always be set to 'new_signature'.

**Comment by vondele** [comment]
I think the 'Defaults to last commit message'  is not working, I appear to need to put an explicit number there. The greyed out fields are on purpose so that base_signature will be new_signature automatically. 

https://github.com/glinscott/fishtest/pull/626
there was a fixup
https://github.com/glinscott/fishtest/pull/630

**Comment by vdbergh** [comment]
'Defaults to last commit message' works perfectly for sprt tests. 

If it is not intended to work for spsa tests then I think the field should be blank.

**Comment by vondele** [comment]
I think it should work :-) just buggy, and filling the field is a workaround.
