### ISSUE TITLE
Make task queue FIFO

### ISSUE THREAD

**Issue by noobpwnftw** [glinscott/fishtest#659]
Factor in (last_update - start_time) of a test in calculating internal priority so that workers that just finished a batch of running tests don't get allocated to a fresh test. This also helps reducing burst downloads from Github due to task switch and prevent spending too many resources on "filler" tests.

**Comment by vondele** [comment]
we had the equivalent of FIFO based on itp adjustment using start_time for a while, but people complained (rightfully so?) that new tests were not starting. A long running LTC would get all resources till it finished. 

However, if I understand correctly, you would like some scheme  in which workers switch tasks as little as possible. Some kind of affinity of workers to tests. Maybe something like... unless there is a task with an itp that is 2x of what I'm doing now, I'm going to stick with my current one (if that still needs compute). Maybe that's something that is not too difficult to implement, don't know if the server has an idea about what workers did in the past.

**Comment by ppigazzini** [comment]
@noobpwnftw If I'm not wrong the Github API rate limit is the underlying problem, in that case we could try to raise the limit with an optional user authentication.

https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/

**Comment by noobpwnftw** [comment]
@ppigazzini When I run a few thousand workers(they use .netrc authentication), it is still easy to hit the limit.

**Comment by tomtor** [comment]
@vondele Not sure how to add this. Currently the allocation of workers is completely fair, a new worker gets its share of workers and is not punished because it is fresh.
I agree that affinity to tests for workers can be a nice property. I'll have to think about how to code that in an elegant way, without changing the fair allocation, might take a while... ;-)

**Comment by vondele** [comment]
I do like our current itp scheme, works really from the user point of view. However, I think we can violate the 'fairness' by a little bit, because it comes at a cost (many recompiles needed). Also, all tests will be treated the same, so it is still fair, it just will ramp up the number of workers assigned to a test a little more slowly. To give an example To give an example 
https://tests.stockfishchess.org/tests/view/5eb050eda460c0e4b8b9bf14   
195 workers jumped on this task, but after about 9000 games it was out. On average 30 games per worker. If we assume about 15sec compilation time (+ extra time for bench etc), that is about 2-3% overhead.

Note that even the itp changes quite quickly over time (as the LLR changes, poor tests have more workers assigned than the fairness would suggest).

**Comment by noobpwnftw** [comment]
Yes, as currently any fresh test will immediately grab quite some workers, and cause burst API requests and recompile, also make old tests finish slower, this leads to more potential recompile in the process. I think it is better off to keep a smaller list of active tests(have a portion of age in itp), let workers stay on their current task so that they either finish or LLR dropped to a level so workers get rescheduled.

**Comment by ppigazzini** [comment]
@noobpwnftw Github nginx cache with conditional requests could work?
https://github.com/Azure/github-nginx-cache
https://developer.github.com/v3/#conditional-requests

**Comment by noobpwnftw** [comment]
Isn't it better if fishtest provides such download cache? Or I'll have to edit worker code and/or modify /etc/hosts and bypass SSL checks. I guess it is also possible to use free plans from Cloudflare to remove bandwidth costs.

**Comment by vondele** [comment]
@noobpwnftw naive question, can't you have something like a shared filesystem on your worker, so the compiled binaries are available for all? Right now might now might not work out of the box, as the compilation process itself might be racy in the same directory, but it could be made to work. In that way you don't only skip the download, but also the compilation.

**Comment by noobpwnftw** [comment]
Yeah well, I could make the orchestration of worker instances include region-local dependencies and add introduce more worker side modifications. However I think that is not future proof and someone else will have to redo the work to run workers at scale. So far the main problem is downloading from Github, local compilation is a good trade because otherwise for each type of machine/OS/version, a compile has to be made, it'd be simpler as is.

**Comment by tomtor** [comment]
#662 might be what we want.

Implementing worker test affinity does not solve the problem when a new test arrives, so I just limit the number of new workers allocated each minute.

**Comment by tomtor** [comment]
I might need to add some code to #662 to not count allocations which work on the same test as the previous allocation...

**Comment by noobpwnftw** [comment]
@tomtor Yes, I think my issue can be solved by throttling workers from the same user to be reallocated to a new test faster than a limit. Preferably when the limit is hit, they get rearranged to previous test if not yet finished.

**Comment by vondele** [comment]
@noobpwnftw is this now resolved in a satisfactory manner with with #662 ?

**Comment by noobpwnftw** [comment]
Yes, thanks!
