### ISSUE TITLE
can't submit tests.

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#663]
Causing an error "string indices must be integers "

**Comment by vondele** [comment]
Cannot find branch in developer repository  
for a test in my case... 
I wonder if the server ran into a github api limit issue ?

**Comment by vondele** [comment]
I see 'string indices must be integers ' on rescheduling a test.

**Comment by silversolver1** [comment]
I've also received both errors when I was trying to submit some SPRT and SPSA tests. I'm primarily receiving the "Cannot find branch in developer repository" one. I only received the "string indices must be integers" one once and was not able to immediately replicate it.

Also, one of the branches that I tried to submit for SPSA tuning (but was unable to because of this error) says it was created an hour ago on my local so the problem has existed since at least then.

**Comment by ppigazzini** [comment]
My fault, I forgot to restore the .netrc after a test :(
Should be fixed now.

**Comment by vondele** [comment]
it is... thanks!
