### ISSUE TITLE
Worker restart fails on msys2 after version update

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#891]
Automatic worker restart after an update always fail on msys2 for @crossbr (Bryan), see
https://groups.google.com/g/fishcooking/c/Fhi5EzRGnFg/m/Fl-pBPdQBgAJ 

```
Finished game 200 (Base-0f3f5d85fb vs New-380941ce51): 1/2-1/2 {Draw by adjudication}
Score of New-380941ce51 vs Base-0f3f5d85fb: 16 - 19 - 165  [0.492] 200
  Task updated successfully in 0.539605s
Server told us task is no longer needed
ERROR: The process "9028" not found.
Wait 3 seconds before upload of PGN...
  Send heartbeat for 01f03d86-c92b-406b-8eb4-726adf005775 ... Pleased to hear from you...
Uploading compressed PGN of 214908 bytes
Task exited
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615042989, 'used': 0}
Updating worker version to 95
Exception accessing host:
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fishtest-worker\\worker-setup-master\\worker\\testing'
```

**Comment by crossbr** [comment]
Same thing again with update to 96.

Finished game 20 (Base-6786816393 vs New-6786816393): 1-0 {White wins by adjudication}
Score of New-6786816393 vs Base-6786816393: 0 - 3 - 16  [0.421] 19
  Send heartbeat for 7f0faf50-818d-4f14-837b-f4b7ffe5cc35 ... bcross-15cores
Finished game 19 (New-6786816393 vs Base-6786816393): 1/2-1/2 {Draw by adjudication}
Score of New-6786816393 vs Base-6786816393: 0 - 3 - 17  [0.425] 20
  Task updated successfully in 0.608972s
Server told us task is no longer needed
ERROR: The process "21032" not found.
Wait 8 seconds before upload of PGN...
Task exited
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615059533, 'used': 0}
Updating worker version to 96
Exception accessing host:
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fishtest-worker\\worker-setup-master\\worker\\testing'
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615059572, 'used': 0}
Updating worker version to 96
Exception accessing host:
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fishtest-worker\\worker-setup-master\\worker\\testing'
  Send heartbeat for 7f0faf50-818d-4f14-837b-f4b7ffe5cc35 ... Pleased to hear from you...
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615059635, 'used': 0}
Updating worker version to 96
Exception accessing host:
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fishtest-worker\\worker-setup-master\\worker\\testing'
  Send heartbeat for 7f0faf50-818d-4f14-837b-f4b7ffe5cc35 ... Pleased to hear from you...

[..]

Fetch task...API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615061245, 'used': 0}
Updating worker version to 96
Exception accessing host:
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fishtest-worker\\worker-setup-master\\worker\\testing'
  Send heartbeat for 7f0faf50-818d-4f14-837b-f4b7ffe5cc35 ... Pleased to hear from you...
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615061308, 'used': 0}
Updating worker version to 96
Exception accessing host:
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\fishtest-worker\\worker-setup-master\\worker\\testing'
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1615061361, 'used': 0}
Updating worker version to 96
Exception accessing host:
Terminated by signal
  Send heartbeat for 7f0faf50-818d-4f14-837b-f4b7ffe5cc35 ... Pleased to hear from you...
Traceback (most recent call last):
  File "worker.py", line 185, in worker
    update()
  File "C:\fishtest-worker\worker-setup-master\worker\updater.py", line 38, in update
    f.write(requests.get(WORKER_URL).content)
  File "C:\fishtest-worker\worker-setup-master\worker\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\fishtest-worker\worker-setup-master\worker\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\fishtest-worker\worker-setup-master\worker\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\fishtest-worker\worker-setup-master\worker\requests\sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\fishtest-worker\worker-setup-master\worker\requests\sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\fishtest-worker\worker-setup-master\worker\requests\sessions.py", line 169, in resolve_redirects
    resp = self.send(
  File "C:\fishtest-worker\worker-setup-master\worker\requests\sessions.py", line 628, in send
    r.content
  File "C:\fishtest-worker\worker-setup-master\worker\requests\models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\fishtest-worker\worker-setup-master\worker\requests\models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\fishtest-worker\worker-setup-master\worker\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\fishtest-worker\worker-setup-master\worker\requests\packages\urllib3\response.py", line 314, in read
    data = self._fp.read(amt)
  File "C:\tools\msys64\mingw64\lib\python3.8\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\tools\msys64\mingw64\lib\python3.8\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\tools\msys64\mingw64\lib\python3.8\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\tools\msys64\mingw64\lib\python3.8\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\tools\msys64\mingw64\lib\python3.8\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "worker.py", line 98, in on_sigint
    raise Exception("Terminated by signal")
Exception: Terminated by signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 512, in <module>
    main()
  File "worker.py", line 508, in main
    success = worker(worker_info, password, remote)
  File "worker.py", line 207, in worker
    time.sleep(random.randint(10, 60))
  File "worker.py", line 98, in on_sigint
    raise Exception("Terminated by signal")
Exception: Terminated by signal
>>>

**Comment by ppigazzini** [comment]
I got the same bug in a sandbox.
Update successful at start time. 
Update unsuccessful at run time, something is blocking the `testing` folder during the `shutil.move()`
https://github.com/glinscott/fishtest/blob/3e6a98bb068bfca9b735120f56e217975e56c5e6/worker/updater.py#L61-L64

Update successful at run time copying the `testing` folder and deleting all the `testing` folder content:
```
        bkp_testing_dir = os.path.join(worker_dir, "_testing_" + time_stamp)

        try:
            copy_tree(testing_dir, bkp_testing_dir)
        except Exception as e:
            print(e, file=sys.stderr)
            traceback.print_exc()              
             
        for filename in os.listdir(testing_dir):
            file_path = os.path.join(testing_dir, filename)
            try:
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)
                elif os.path.isdir(file_path):
                    shutil.rmtree(file_path)
            except Exception as e:
                print("Failed to delete {}".format(file_path, e))
                print(e, file=sys.stderr)
                traceback.print_exc() 
```

**Comment by ppigazzini** [comment]
@crossbr the worker itself is blocking the `testing` folder :)
https://github.com/glinscott/fishtest/blob/3e6a98bb068bfca9b735120f56e217975e56c5e6/worker/games.py#L903

So the fix is simply change folder before moving the `testing` folder:
```python
def update(restart=True, test=False):
    worker_dir = os.path.dirname(os.path.realpath(__file__))
    os.chdir(worker_dir)
```

**Comment by ppigazzini** [comment]
@crossbr pushed the bugfix, this will work with the next update. My fault to have tested the msys2 update only at start time :(
Thank you for the report :)

**Comment by ppigazzini** [comment]
@d3vv please check your workers on Windows
