### ISSUE TITLE
worker sets wrong CPU factor

### ISSUE THREAD

**Issue by alg4032** [glinscott/fishtest#94]
Worker takes a CPU factor that is lower than usual for my CPU.

see attached log file:
[fishtest_worker_log_file.txt](https://github.com/glinscott/fishtest/files/590180/fishtest_worker_log_file.txt)

I started the worker, it ran benchmarks which showed about 1570 Knodes/second both.
Then engine match started with

> CPU factor : 1.022074 - tc adjusted to 10.22+0.10

The nodes number is way too low for my CPU which is a Intel Core i7-6800K @ 4GHz. Usual number is 2500Knodes. Local bench made by myself:
[bench_test_locally.txt](https://github.com/glinscott/fishtest/files/590181/bench_test_locally.txt)
I stopped the worker with Ctrl+C and started it again immediately.

> 
> $ ./stockfish_start_5.sh 
> Worker version 59 connecting to http://tests.stockfishchess.org:80
> Verifying signature of stockfish ...
> Verifying signature of base ...
> CPU factor : 0.613244 - tc adjusted to 6.13+0.06

The new CPU factor looks correct and might be one that was used before (?). No benchmarks were rerun so I can't explain where it took the correct CPU factor from the second time I started it. It was the first time I started the worker today and all current tests on fishtest were created today.

When the 1000 game completed I started the worker again and received again bench numbers:
> ===========================
> Total time (ms) : 3032
> Nodes searched  : 4735038
> Nodes/second    : 1561687

The match started with a correct CPU factor again:
> Step 4/4. Deleting profile data ...
> make ARCH=x86-64-modern COMP=gcc gcc-profile-clean
> make[1]: Entering directory '/tmp/tmpPuEMnR/GuardianRM-Stockfish-876f07c/src'
> make[1]: Leaving directory '/tmp/tmpPuEMnR/GuardianRM-Stockfish-876f07c/src'
> Verifying signature of stockfish ...
> Verifying signature of base ...
> CPU factor : 0.609349 - tc adjusted to 6.09+0.06

Is this a bug or am I understanding something wrong?

**Comment by ppigazzini** [comment]
On Linux the problem could be due to the CPU increasing speed from idle state.

Try this:
1. Install the cpupower command
2. Run    # cpupower frequency-set --governor performance

Check this thread as reference

https://groups.google.com/d/msg/fishcooking/nk0rr-wVq-k/KCUXmC7zGAAJ

**Comment by alg4032** [comment]
Didn't help unfortunately.
> $ cpupower frequency-info
> analyzing CPU 0:
>   driver: intel_pstate
>   CPUs which run at the same hardware frequency: 0
>   CPUs which need to have their frequency coordinated by software: 0
>   maximum transition latency: 0.97 ms.
>   hardware limits: 1.20 GHz - 4.00 GHz
>   available cpufreq governors: performance, powersave
>   current policy: frequency should be within 1.20 GHz and 4.00 GHz.
>                   The governor "performance" may decide which speed to use
>                   within this range.
>   current CPU frequency is 4.00 GHz.

When idle I get CPU frequencies 2.57GHz to 4.0GHz. I started fishtest again and now repeatedly executed the command above when the benchmarks were running. Each time it has shown me 4.00GHz. So "performance" mode seems to be active and keeps the frequency at 4.00GHz. When I started fishtest again I saw the same problem as described above.

The CPU factor is just inconsistent. Benchmark values are always too low, CPU factor for the engine match is sometimes correct (about 0.6 and I don't know where it comes from),  sometimes not (based on benchmark numbers: about 1.0).

**Comment by ppigazzini** [comment]
CPU factor depends also on the number of threads used in fishtest (concurrency)
It is computed in games.py, running:
1. in verify_signature():
  a. a first process that load the CPU with n. threads -1 when using fishtest with concurrency > 1  (using "strockfish" "go infinite" with n. threads -1)
  b. a second process that computes the bench number with 1 thread ("stockfish bench")
2. in adjust_tc(): normalizing the tc according to the bench number

Here you can view how change the bench number according to the concurrency

https://groups.google.com/d/msg/fishcooking/2gswm_us0bs/IR1hTILSCwAJ

Hope this help

**Comment by ppigazzini** [comment]
Anyway your CPU factor ratio (1.022074/0.613244=1.666) is very similar to your CPU frequency ratio (4.00/2.57=1.556): try to enforce the performance mode and check if this solve the problem.

In alternative you can add in games.py a time.sleep(1) at line 67 (this work only if you start fishtest with concurrency > 1)

def verify_signature(engine, signature, remote, payload, concurrency):
  if concurrency > 1:
    busy_process = subprocess.Popen([engine], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    busy_process.stdin.write('setoption name Threads value %d\n' % (concurrency-1))
    busy_process.stdin.write('go infinite\n')
    time.sleep(1)
  try:
    bench_sig = ''
    print 'Verifying signature of %s ...' % (os.path.basename(engine))

**Comment by alg4032** [comment]
Thank you so far.

I didn't understand why n-1 threads are running while the last thread is getting benchmarked but I tried this myself without fishtest and the last 6th core gets a bench number of ~2450 when others are fully loaded. In idle state I get ~2550 as mentioned above.

I tried the time.sleep(1) command too, still get ~1550 knodes/s in the benchmark but a CPU factor of 0.615.

CPU frequency 2.57GHz is just one of the lower number I picked from the numbers I get when executing
> $ cpupower frequency-info
Sometimes its 2.97 or 2.33GHz.
>   hardware limits: 1.20 GHz - 4.00 GHz
>   available cpufreq governors: performance, powersave
>   current policy: frequency should be within 4.00 GHz and 4.00 GHz.
>                   The governor "performance" may decide which speed to use
>                   within this range.
>   current CPU frequency is 2.97 GHz.
I found out how to set the lower frequency bound to 4.00GHz and performance mode is on. I'm also sure that the cpu frequency is constantly at 4.00GHz when the benchmark is running. So still unclear what is happening.

**Comment by ppigazzini** [comment]
You have a fast CPU, your correct CPU factor is ~ 0.6, the wrong one is 1.0

"stockfish bench" is deterministic only for 1 thread. So to compute the CPU performance with concurrency = N, we load N-1 threads with the first process ("stockfish setoption name Threads value N-1 go infinite") and then we start the second process ("stockfish bench") to bench (in deterministic way) the CPU with 1 threads (but with the CPU loaded with N threads).

Here the result for my i7 3770k (4 core + HT): you can view that the bench number decreases when the concurrency increases (there is a big jump when are used the virtual cores)

concurrency = 1   mean = 2507653
concurrency = 2   mean = 2513069
concurrency = 3   mean = 2487114
concurrency = 4   mean = 2463138
concurrency = 5   mean = 2292671
concurrency = 6   mean = 1793011
concurrency = 7   mean = 1692038
concurrency = 8   mean = 1682409

If your problem is due to the (lazy) Linux algorithms for the CPU power saving, adding a time.sleep(1) before the "stockfish bench" process should solve the problem to compute the correct CPU factor (I think that 1 second is sufficient to have the CPU topping the 4.00 GHz).

But this works only for concurrency >1 and only during the CPU bench. I don't know if the CPU frequency changes during fishtest.

Setting the CPU at 4.00 GHz with "cpupower" is the only safe option: it works also with concurrency=1 and it works also during fishtest.

Unfortunately I don't have any native Linux machine to performs the debugging (i.e. monitoring the CPU frequency for 24h during fishtest).

Many Linux workers could have this problem, crippling the tests in fishtest :(
