### ISSUE TITLE
[Related #952] Inconsistent code in games.py

### ISSUE THREAD

**Issue by proukornew** [glinscott/fishtest#956]
I've reviewed setup_engine function. It **probably** contains environment bug, that can be short described as:
```
>>> print(os.environ['PWD'])
/home/Open/stockfish/Stockfish/src
>>> os.chdir('./nnue')
>>> print(os.environ['PWD'])
/home/Open/stockfish/Stockfish/src
>>>print(os.cwd())
/home/Open/stockfish/Stockfish/src/nnue
```
Due to #952, it's clear, that in scope of subprocess.check_call are using another (old?) cwd string
`[fishtest@thaumaturgia worker]$ find tmpm4bt28nr -name *psqt.gcda
tmpm4bt28nr/SFisGOD-Stockfish-7f720b9/src/profdir/#home#fishtest#fishtest#worker#tmpe880ldqh#SFisGOD-Stockfish-def85a7#src#psqt.gcda
`
Should be
`[fishtest@thaumaturgia worker]$ find tmpm4bt28nr -name *psqt.gcda
tmpm4bt28nr/SFisGOD-Stockfish-7f720b9/src/profdir/#home#fishtest#fishtest#worker#tmpm4bt28nr#SFisGOD-Stockfish-7f720b9#src#psqt.gcda
`

I propose patch, but i **didn't test** it myself. Help is appreciated.
https://github.com/proukornew/fishtest/commit/0f84b74e7afb70487484fec87a0664065d93e9ff

**Comment by ppigazzini** [comment]
@proukornew we test each fishtest PR with [DEV](https://dfts-0.pigazzini.it/) and some workers (linux ubuntu, wsl2 ubuntu, msys2). This night I will setup a vm with fedora 33.
Thank you for your help :)

**Comment by ppigazzini** [comment]
@proukornew 
https://docs.python.org/3/library/os.html#os.environ
"This mapping is captured the first time the os module is imported, typically during Python startup as part of processing site.py. Changes to the environment made after this time are not reflected in os.environ, except for changes made by modifying os.environ directly."

By the way `print(subprocess.check_call("pwd", shell=True, env=dict(os.environ)))` on my systems reflects the `os.chdir()`

```
>>> import os
>>> import subprocess
>>> print(os.getcwd())
/home/usr00
>>> print(os.environ["PWD"])
/home/usr00
>>> os.chdir("__tmp")
>>> print(os.getcwd())
/home/usr00/__tmp
>>> print(os.environ["PWD"])
/home/usr00
>>> print(subprocess.check_call("pwd", shell=True, env=dict(os.environ)))
/home/usr00/__tmp
0
```

**Comment by proukornew** [comment]
Test on fresh Fedora-Workstation-Live-x86_64-33-1.2 & fresh fishtest: no warnings achieved.

**Comment by gvreuls** [comment]
@proukornew Yes, I picked up my other worker from another location and my second worker, which also runs Fedora 33 but is still on Python 3.9.2, doesn't produce the warnings either.

I'm now running dnf update to test whether Python 3.9.5 is the culprit (which will take a while).

**Comment by ppigazzini** [comment]
@proukornew IMO something like this should be more robust:

```python
        ARCH = find_arch_string()

        make_env = os.environ.copy()

        make_env["PWD"], err = subprocess.Popen(["pwd"],
        stdout=subprocess.PIPE,
        universal_newlines=True,
        bufsize=1,
        close_fds=not IS_WINDOWS,
        ).communicate()

        subprocess.check_call(
            MAKE_CMD + ARCH + " -j {}".format(concurrency) + " profile-build",
            shell=True,
            env=dict(make_env, CXXFLAGS="-DNNUE_EMBEDDING_OFF"),
        )
```

**Comment by ppigazzini** [comment]
@gvreuls python 3.9.5 (provided by pyenv) is fine in my Ubuntu 20.04 and WSL2 Ubuntu 20.04

**Comment by gvreuls** [comment]
@proukornew @ppigazzini My second worker is now updated but it **doesn't produce the warnings**, so I'm afraid this is a false alert and it's just my primary worker running haywire. I'm investigating what causes the warnings and report if I find something. Sorry.

**Comment by ppigazzini** [comment]
Anyway @proukornew is right about the potential bug on passing the wrong "PWD" environment variable, so I'm keeping this Issue open for further analysis.

**Comment by proukornew** [comment]
@ppigazzini. Does fishtest produce 2 binaries in serial-way (no race condition)?

**Comment by ppigazzini** [comment]
Yes, `subprocess.check_call()` wait for command to complete.
https://docs.python.org/3.8/library/subprocess.html?highlight=subprocess#subprocess.check_call

**Comment by proukornew** [comment]
@ppigazzini Does fishtest use incremental builds?

**Comment by ppigazzini** [comment]
@proukornew it seems that `shell=True` sets always the right `PWD` (to be tested on different platform)

```
>>> os.chdir("__tmp")

>>> subprocess.check_call("env", env=dict(PWD="goofy"))
PWD=goofy
0

>>> subprocess.check_call("env", shell=True, env=dict(PWD="goofy"))
PWD=/home/usr00
0

>>> subprocess.check_call("env")
...
PWD=/home/usr00
LOGNAME=usr00
HOME=/home/usr00
LANG=C.UTF-8
...

>>> subprocess.check_call("env", shell=True)
PWD=/home/usr00/__tmp
PYENV_ROOT=/home/usr00/.pyenv
```

**Comment by ppigazzini** [comment]
> @ppigazzini Does fishtest use incremental builds?

fishtest check if there is already a binary built, otherwise downloads the stockfish archive from GitHub, expands the files in a random temporary directory, calls `make`, remove the temporary directory.

**Comment by gvreuls** [comment]
@proukornew @ppigazzini The warnings are caused by the ``ccache`` compiler cache. If I clear the compiler cache with ``ccache -C`` the first build completes without warnings but the warnings reappear with the second build.

What happens is that ``ccache`` caches the instrumented object files created by ``-fprofile-generate=profdir`` in step 1 of the Makefile ``profile-build``, but it doesn't cache the optimized object files  created by ``-fprofile-use=profdir`` in step 3 and compiles them every time anew. This is the sequence:
1. From the second build on the cached instrumented object files are used in to build an instrumented binary in step 1 of the ``make profile-build`` process,
2. which forces the instrumented binary to write its .gcda files to a nonexistent temporary directory (that was deleted by the worker after an earlier build) when it is run in step 2, which _fails silently_ .
3. This is followed by step 3 rightfully complaining that the .gcda files aren't there.

I'm now searching for a way to configure ``ccache`` so it doesn't cache object files for the worker, if that isn't possible I'll get rid of it.

**Comment by gvreuls** [comment]
Disabling ``ccache`` turns out to be very simple, setting ``CCACHE_DISABLE="1"`` in the environment is enough to fix the warnings.

https://github.com/glinscott/fishtest/blob/fc0a51cae3085f6c389398a1a31820e319162620/worker/games.py#L418-L422

@ppigazzini perhaps add ``CCACHE_DISABLE="1" `` so this won't happen to other users with ``ccache`` installed?

```Python
           env=dict(os.environ, CXXFLAGS="-DNNUE_EMBEDDING_OFF", CCACHE_DISABLE="1"),
```

**Comment by proukornew** [comment]
@gvreuls
ccache 3.7.10
Release date: 2020-06-22

Bug fixes
Improved handling of profiling options. ccache should now work correctly for profiling options like -fprofile-{generate,use}[=path] for GCC ≥ 9 and Clang as well as -fauto-profile[=path] and the Clang-specific -fprofile-instr-{generate,use}[=path] and -fprofile-sample-{use,accurate} options.

**Comment by ppigazzini** [comment]
@proukornew the actual code seems to be fine:
- on Linux `shell=True` rewrites the `PWD` variable
- on Windows the `PWD` environment variable hasn't any meaning with any combination of python/cli (msys2 python or windows python / msys2 shell or powershell or cmd)
